on: [push]

jobs:
  build:
    name: conda-test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            prefix: /usr/share/miniconda3/envs/test
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
        with:
          path: 'src'

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: "latest"
          python-version: 3.8
          use-only-tar-bz2: true # for caching

      # restore from cache
      - name: Restore environment
        id: restore-env-cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ matrix.prefix }}
          key: ${{ runner.os }}-env

      - name: Install conda-build
        run: conda install conda-build

      - name: Build package
        run: conda build conda-recipe
        working-directory: src/

      - name: Save environment
        id: save-env-cache
        uses: actions/cache/save@v3
        with:
          path: ${{ matrix.prefix }}
          key: ${{ steps.restore-env-cache.outputs.cache-primary-key }}
